### ISSUE TITLE
Generierung des Nachweises (PDF Ticket) als Subressource vom Ticket

### ISSUE THREAD

**Issue by SBejga** [Lockdown-WirVsVirus/safeticket-api#8]

**Comment by markory** [comment]
@SBejga kann das Issue ins Frontend verschoben werden, oder sollen wir probieren es im Backend zu generieren?

**Comment by SBejga** [comment]
In der Theorie geht es auch im Frontend ja, aber sollte das PDF nicht immer vom Backend generiert werden?
